Allows process names to include numbers. Removes unused isString function. The process name handling was too restrictive and would not allow numbers to be used.

diff --git a/checksec b/checksec
--- a/checksec
+++ b/checksec
@@ -501,19 +501,18 @@ chk_proc() {
     exit 1
   fi
   cd /proc || exit
-  if (isString "${CHK_PROC}"); then
-    IFS=" " read -r -a fpids <<< "$(pgrep -d ' ' "${CHK_PROC}")"
-  elif (isNumeric "${CHK_PROC}"); then
-    fpids=("${CHK_PROC}")
-  else
-    printf "\033[31mError: Please provide a valid process name or pid.\033[m\n\n"
-    exit 1
+  # assume a process name was given
+  IFS=" " read -r -a fpids <<< "$(pgrep -d ' ' "${CHK_PROC}")"
+  # if nothing was found check if it is a PID
+  if [[ ${#fpids} -eq 0 ]]; then
+    if (isNumeric "${CHK_PROC}") && [[ -n "$(ps -p "${CHK_PROC}" -o pid=)" ]]; then
+      fpids=("${CHK_PROC}")
+    else
+      printf "\033[31mError: Please provide a valid process name or pid.\033[m\n\n"
+      exit 1
+    fi
   fi
 
-  if [[ ${#fpids} -eq 0 ]]; then
-    printf "\033[31mError: No process with the given name or pid found.\033[m\n\n"
-    exit 1
-  fi
   echo_message "* System-wide ASLR" '' '' ''
   aslrcheck
   echo_message "* Does the CPU support NX: " '' '' ''
@@ -947,11 +946,6 @@ echo_message() {
 # check if input is numeric
 isNumeric() {
   echo "$@" | grep -q -v "[^0-9]"
-}
-
-# check if input is a string
-isString() {
-  echo "$@" | grep -q -v "[^ A-Z_a-z]"
 }
 
 # help
